In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def softmax(values):
    s = np.sum(np.exp(values))
    return np.exp(values) / s

data = np.array([1, 2, 3, 4, 5])
print(softmax(data))
print(np.sum(data * softmax(data)))

[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]
4.451941567662194


In [3]:
def attention(query, keys, values):
    scores = query * keys    # per-component multiplication
    #print(query.shape)
    #print(keys.shape)
    #print(scores)
    scores = np.sum(scores, axis = 1)   # dot product
    #print(scores.shape)
    print(scores)
    probs = softmax(scores)
    print(" ".join(map(lambda x: "{:.3f}".format(x), probs)))
    result = (values.T * probs).T
    #print(result)
    return np.sum(result, axis = 0)

print(attention(
    np.array([-1, 2, 3]),
    np.array([
        [-1, 3, -1],
        [1.5, 1.5, 2.5],
    ]),
    np.array([
        [-1, 3, -1],
        [1.5, 1.5, 2.5]
    ])
))
print("")
print(attention(
    np.array([-1, 2, -3]),
    np.array([
        [-1, 3, -1],
        [1.5, 1.5, 2.5],
    ]),
    np.array([
        [-1, 3, -1],
        [1.5, 1.5, 2.5]
    ])
))


[4. 9.]
0.007 0.993
[1.48326787 1.51003928 2.47657502]

[10. -6.]
1.000 0.000
[-0.99999972  2.99999983 -0.99999961]
