In [6]:
import torch

a = torch.tensor([
    [[1, 2], [2, 1]],
    [[1, 0], [0, 1]],
    [[1, -1], [2, -1]],
], dtype = torch.float32)

b = torch.tensor(
    [[1, 2], [2, 1]],
    dtype = torch.float32
)

print(a)
print(a.shape)
print("")

print(b)
print(b.shape)

tensor([[[ 1.,  2.],
         [ 2.,  1.]],

        [[ 1.,  0.],
         [ 0.,  1.]],

        [[ 1., -1.],
         [ 2., -1.]]])
torch.Size([3, 2, 2])

tensor([[1., 2.],
        [2., 1.]])
torch.Size([2, 2])


In [7]:
a[0] @ b

tensor([[5., 4.],
        [4., 5.]])

In [9]:
torch.matmul(a[2], b)

tensor([[-1.,  1.],
        [ 0.,  3.]])

In [10]:
a @ b

tensor([[[ 5.,  4.],
         [ 4.,  5.]],

        [[ 1.,  2.],
         [ 2.,  1.]],

        [[-1.,  1.],
         [ 0.,  3.]]])